# Generated by Django 3.0.3 on 2020-07-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapp', '0002_auto_20200721_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatordata',
            name='operation',
            field=models.CharField(default=False, max_length=1),
        ),
    ]
